- file: path={{ virtualenv_base_path }} state=directory owner=www-data group=www-data
  sudo: true

- name: Manually create the initial virtualenv
  command: virtualenv -p python3 {{ virtualenv_path }} creates="{{ virtualenv_path }}"
  become: yes
  become_user: www-data

- name: Setup Virtualenv requirements
  pip: virtualenv={{ virtualenv_path }} requirements={{ app_path }}/requirements.txt
  become: yes
  become_user: www-data
  notify:
    - Restart Uwsgi

- name: Add Gourmand Uwsgi app
  sudo: yes
  template: src=gourmand_uwsgi.ini.j2 dest=/etc/uwsgi/apps-available/gourmand.ini owner=root group=root mode=0660
  notify:
    - Restart Uwsgi

- name: Collect Django static files
  django_manage:
    command=collectstatic
    app_path={{app_path}}
    virtualenv={{virtualenv_path}}
  environment:
    SECRET_KEY: "{{secret_key}}"
    DATABASE_URL: "{{database_url}}"

- name: Apply Django migrations
  django_manage:
    command=migrate
    app_path={{app_path}}
    virtualenv={{virtualenv_path}}
  environment:
    SECRET_KEY: "{{secret_key}}"
    DATABASE_URL: "{{database_url}}"

- name: Enable Gourmand Uwsgi app
  sudo: yes
  file: src=/etc/uwsgi/apps-available/gourmand.ini dest=/etc/uwsgi/apps-enabled/gourmand.ini state=link
  notify:
    - Restart Uwsgi
