- name: Install Postgres
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql
    - python-psycopg2

- name: Create Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create Database User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present

- name: Provide Database User with Permissions Over Database
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL
