- name: Install Django stack packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    # Nginx
    - nginx

    # Database
    - postgresql
    - libpq-dev
    - python-psycopg2

    # Python3
    - python-virtualenv
    - python3-dev

- name: Disable Default Nginx Site
  sudo: yes
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add Gourmand Nginx Site
  sudo: yes
  template: src=gourmand_nginx.j2 dest=/etc/nginx/sites-available/gourmand owner=root group=root

- name: Enable Gourmand Nginx Site
  sudo: yes
  file: src=/etc/nginx/sites-available/gourmand dest=/etc/nginx/sites-enabled/gourmand state=link
  notify:
    - Restart Nginx

- name: Create Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL
