- name: Install Gourmand Webapp packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    # Uwsgi
    - uwsgi
    - uwsgi-plugin-python3
    # Gourmand requirements
    - python-virtualenv
    - python3-dev
    - libpq-dev

- name: Create the virtualenv base directory
  file: path={{ virtualenv_base_path }} state=directory
  sudo: true

- name: Manually create the initial virtualenv
  command: virtualenv -p python3 {{ virtualenv_path }} creates="{{ virtualenv_path }}"
  sudo: true

- name: Setup Virtualenv requirements
  pip: virtualenv={{ virtualenv_path }} requirements={{ app_path }}/requirements.txt
  sudo: true
  notify:
    - Restart Uwsgi

- name: Add Gourmand Uwsgi app
  sudo: true
  template: src=gourmand_uwsgi.ini.j2 dest=/etc/uwsgi/apps-available/gourmand.ini owner=root group=root mode=0664
  notify:
    - Restart Uwsgi

- name: Add Gourmand settings to profiles.d
  sudo: true
  template: src=gourmand.sh.j2 dest=/etc/profile.d/gourmand.sh owner=root group=root mode=0775

- name: Collect Django static files
  django_manage:
    command=collectstatic
    app_path={{app_path}}
    virtualenv={{virtualenv_path}}
  environment:
    SECRET_KEY: "{{django_secret}}"
    DATABASE_URL: "{{db_url}}"

- name: Apply Django migrations
  django_manage:
    command=migrate
    app_path={{app_path}}
    virtualenv={{virtualenv_path}}
  environment:
    SECRET_KEY: "{{django_secret}}"
    DATABASE_URL: "{{db_url}}"

- name: Enable Gourmand Uwsgi app
  sudo: true
  file: src=/etc/uwsgi/apps-available/gourmand.ini dest=/etc/uwsgi/apps-enabled/gourmand.ini state=link
  notify:
    - Restart Uwsgi
